spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:cars_db}
    username: ${POSTGRES_USER:cars}
    password: ${POSTGRES_PASSWORD:cars}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect